# PostgreSQL. Versions 9.4 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: person_registrations
  password: person_registrations

development:
  <<: *default
  database: person_registrations_development

test:
  <<: *default
  database: person_registrations_test

production:
  <<: *default
  database: person_registrations_production
